#!/usr/bin/env bash
set -euo pipefail

ROOT="/var/www/aiir"
TUNE_FILE="${ROOT}/server/env/ai-first-tuning.env"
MODE="write"

usage() {
  cat >&2 <<'USAGE'
usage:
  /var/www/aiir/server/scripts/aiir-tune-self.sh [--print|--write]

modes:
  --print  print computed AI-first tuning profile to stdout
  --write  write/update /var/www/aiir/server/env/ai-first-tuning.env (default)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --print)
      MODE="print"
      shift ;;
    --write)
      MODE="write"
      shift ;;
    -h|--help)
      usage
      exit 0 ;;
    *)
      echo "unknown arg: $1" >&2
      usage
      exit 1 ;;
  esac
done

cpu="$(nproc 2>/dev/null || echo 2)"
mem_kib="$(awk '/MemTotal:/ {print $2; exit}' /proc/meminfo 2>/dev/null || echo 4194304)"
mem_mib="$((mem_kib / 1024))"

# Runtime defaults (AI-first balanced and conservative under lower resources).
if [[ "$cpu" -ge 16 ]]; then
  rate_limit="180"
  io_timeout="2200"
  cb_threshold="30"
elif [[ "$cpu" -ge 8 ]]; then
  rate_limit="120"
  io_timeout="2000"
  cb_threshold="24"
else
  rate_limit="80"
  io_timeout="1800"
  cb_threshold="20"
fi

if [[ "$mem_mib" -ge 16000 ]]; then
  full_analysis_mb="500"
  ingest_timeout="2400"
  parity_timeout="900"
  html_max_files="180"
  css_max_files="180"
  js_max_files="180"
elif [[ "$mem_mib" -ge 8000 ]]; then
  full_analysis_mb="400"
  ingest_timeout="1800"
  parity_timeout="750"
  html_max_files="150"
  css_max_files="150"
  js_max_files="150"
else
  full_analysis_mb="300"
  ingest_timeout="1500"
  parity_timeout="650"
  html_max_files="120"
  css_max_files="120"
  js_max_files="120"
fi

content=$(cat <<ENV
# Auto-generated by aiir-tune-self.sh
# Host profile: cpu=${cpu} mem_mib=${mem_mib}
# AI-first balanced tuning for runtime + benchmark.
AI_RATE_LIMIT_RPS=${rate_limit}
AI_IO_TIMEOUT_MS=${io_timeout}
AI_CB_FAIL_THRESHOLD=${cb_threshold}
AIIR_FULL_ANALYSIS_MAX_MB=${full_analysis_mb}
AIIR_INGEST_TIMEOUT_SEC=${ingest_timeout}
AIIR_PARITY_TIMEOUT_SEC=${parity_timeout}
OAIIR_HTML_MAX_FILES=${html_max_files}
OAIIR_CSS_MAX_FILES=${css_max_files}
OAIIR_JS_MAX_FILES=${js_max_files}
ENV
)

if [[ "$MODE" == "print" ]]; then
  printf '%s\n' "$content"
  exit 0
fi

mkdir -p "$(dirname "$TUNE_FILE")"
printf '%s\n' "$content" > "$TUNE_FILE"

cat <<EOF2
{"ok":1,"action":"tune_self","mode":"write","file":"${TUNE_FILE}","cpu":${cpu},"mem_mib":${mem_mib},"ai_rate_limit_rps":${rate_limit},"ai_io_timeout_ms":${io_timeout},"aiir_full_analysis_max_mb":${full_analysis_mb},"aiir_ingest_timeout_sec":${ingest_timeout},"aiir_parity_timeout_sec":${parity_timeout}}
EOF2
