#!/usr/bin/env bash
set -euo pipefail

SRC_DIR="${1:-}"
CONVERT_OUT_DIR="${2:-}"

usage() {
  cat >&2 <<'USAGE'
usage:
  /var/www/aiir/server/scripts/aiir-parity-check.sh <source-dir> <convert-out-dir>
notes:
  - convert-out-dir must contain normalized-web generated by aiir-convert-project.sh
USAGE
}

if [[ -z "$SRC_DIR" || -z "$CONVERT_OUT_DIR" ]]; then
  usage
  exit 1
fi
if [[ ! -d "$SRC_DIR" ]]; then
  echo '{"ok":0,"err":"source_dir"}'
  exit 1
fi

NORM_DIR="${CONVERT_OUT_DIR}/normalized-web"
if [[ ! -d "$NORM_DIR" ]]; then
  echo '{"ok":0,"err":"normalized_web"}'
  exit 1
fi

TMPDIR="$(mktemp -d)"
cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

src_web="${TMPDIR}/src-web.txt"
norm_web="${TMPDIR}/norm-web.txt"
rg --files -uu "$SRC_DIR" -g '*.html' -g '*.htm' -g '*.css' -g '*.scss' -g '*.js' -g '*.jsx' -g '*.ts' -g '*.tsx' | sed "s#^${SRC_DIR}/##" | sort -u > "$src_web"
rg --files -uu "$NORM_DIR" -g '*.html' -g '*.htm' -g '*.css' -g '*.scss' -g '*.js' -g '*.jsx' -g '*.ts' -g '*.tsx' | sed "s#^${NORM_DIR}/##" | sort -u > "$norm_web"

src_count="$(wc -l < "$src_web" | awk '{print $1}')"
norm_count="$(wc -l < "$norm_web" | awk '{print $1}')"
matched_count="$(comm -12 "$src_web" "$norm_web" | wc -l | awk '{print $1}')"
logic_parity="$(awk -v m="$matched_count" -v s="$src_count" 'BEGIN {if (s<=0) printf "0.00"; else printf "%.2f", (m/s)*100}')"

extract_logic_tokens() {
  local base="$1"
  local out="$2"
  : > "$out"
  if [[ -d "$base" ]]; then
    rg -uu -o --no-filename 'fetch\([^)]*\)|axios\.[a-z]+\([^)]*\)|action="[^"]+"|href="[^"]+"' "$base" -g '*.html' -g '*.htm' -g '*.js' -g '*.jsx' -g '*.ts' -g '*.tsx' 2>/dev/null \
      | sed -E 's/^.*"([^"]+)".*$/\1/' \
      | sed -E "s/^['\"]?//; s/['\"]?$//" \
      | rg -v '^https?://' \
      | sort -u > "$out" || true
  fi
}

src_tokens="${TMPDIR}/src-tokens.txt"
norm_tokens="${TMPDIR}/norm-tokens.txt"
extract_logic_tokens "$SRC_DIR" "$src_tokens"
extract_logic_tokens "$NORM_DIR" "$norm_tokens"

src_tok_count="$(wc -l < "$src_tokens" | awk '{print $1}')"
match_tok_count="$(comm -12 "$src_tokens" "$norm_tokens" | wc -l | awk '{print $1}')"
logic_token_parity="$(awk -v m="$match_tok_count" -v s="$src_tok_count" 'BEGIN {if (s<=0) printf "100.00"; else printf "%.2f", (m/s)*100}')"

# Visual parity proxy: identical file hashes for shared HTML/CSS files.
shared_visual="${TMPDIR}/shared-visual.txt"
comm -12 <(rg --files -uu "$SRC_DIR" -g '*.html' -g '*.htm' -g '*.css' -g '*.scss' | sed "s#^${SRC_DIR}/##" | sort -u) \
         <(rg --files -uu "$NORM_DIR" -g '*.html' -g '*.htm' -g '*.css' -g '*.scss' | sed "s#^${NORM_DIR}/##" | sort -u) \
  > "$shared_visual"

shared_count="$(wc -l < "$shared_visual" | awk '{print $1}')"
identical=0
while IFS= read -r rel; do
  [[ -z "$rel" ]] && continue
  if [[ -f "$SRC_DIR/$rel" && -f "$NORM_DIR/$rel" ]]; then
    h1="$(sha256sum "$SRC_DIR/$rel" | awk '{print $1}')"
    h2="$(sha256sum "$NORM_DIR/$rel" | awk '{print $1}')"
    if [[ "$h1" == "$h2" ]]; then
      identical=$((identical+1))
    fi
  fi
done < "$shared_visual"

visual_parity="$(awk -v i="$identical" -v s="$shared_count" 'BEGIN {if (s<=0) printf "0.00"; else printf "%.2f", (i/s)*100}')"

overall="$(awk -v a="$logic_parity" -v b="$logic_token_parity" -v c="$visual_parity" 'BEGIN {printf "%.2f", (a+b+c)/3}')"

cat <<EOF2
{"ok":1,"action":"parity_check","source_web_files":${src_count},"normalized_web_files":${norm_count},"logic_file_parity":${logic_parity},"logic_token_parity":${logic_token_parity},"visual_parity":${visual_parity},"overall_parity":${overall},"targets":{"logic":100.00,"visual":100.00}}
EOF2
