#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/var/www/aiir/server/env/ai-runtime.env"
RUNTIME_BIN="/var/www/aiir/ai/toolchain-native/aiird"

CLI_AI_CORE_DIR="${AI_CORE_DIR-}"
CLI_AI_RUNTIME_HOST="${AI_RUNTIME_HOST-}"
CLI_AI_RUNTIME_PORT="${AI_RUNTIME_PORT-}"
CLI_AI_DB_EXEC_MODE="${AI_DB_EXEC_MODE-}"
CLI_AI_POLICY_ALLOW_DB_EXEC="${AI_POLICY_ALLOW_DB_EXEC-}"
CLI_AI_POLICY_ALLOW_OPS="${AI_POLICY_ALLOW_OPS-}"
CLI_AI_WAL_PATH="${AI_WAL_PATH-}"
CLI_AI_SNAPSHOT_PATH="${AI_SNAPSHOT_PATH-}"
CLI_AI_MAX_REQ_BYTES="${AI_MAX_REQ_BYTES-}"
CLI_AI_MAX_BODY_BYTES="${AI_MAX_BODY_BYTES-}"
CLI_AI_IO_TIMEOUT_MS="${AI_IO_TIMEOUT_MS-}"
CLI_AI_RATE_LIMIT_RPS="${AI_RATE_LIMIT_RPS-}"
CLI_AI_CB_FAIL_THRESHOLD="${AI_CB_FAIL_THRESHOLD-}"
CLI_AI_CB_COOLDOWN_SEC="${AI_CB_COOLDOWN_SEC-}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

if [[ -n "$CLI_AI_CORE_DIR" ]]; then AI_CORE_DIR="$CLI_AI_CORE_DIR"; fi
if [[ -n "$CLI_AI_RUNTIME_HOST" ]]; then AI_RUNTIME_HOST="$CLI_AI_RUNTIME_HOST"; fi
if [[ -n "$CLI_AI_RUNTIME_PORT" ]]; then AI_RUNTIME_PORT="$CLI_AI_RUNTIME_PORT"; fi
if [[ -n "$CLI_AI_DB_EXEC_MODE" ]]; then AI_DB_EXEC_MODE="$CLI_AI_DB_EXEC_MODE"; fi
if [[ -n "$CLI_AI_POLICY_ALLOW_DB_EXEC" ]]; then AI_POLICY_ALLOW_DB_EXEC="$CLI_AI_POLICY_ALLOW_DB_EXEC"; fi
if [[ -n "${CLI_AI_POLICY_ALLOW_OPS+x}" ]]; then AI_POLICY_ALLOW_OPS="$CLI_AI_POLICY_ALLOW_OPS"; fi
if [[ -n "$CLI_AI_WAL_PATH" ]]; then AI_WAL_PATH="$CLI_AI_WAL_PATH"; fi
if [[ -n "$CLI_AI_SNAPSHOT_PATH" ]]; then AI_SNAPSHOT_PATH="$CLI_AI_SNAPSHOT_PATH"; fi
if [[ -n "$CLI_AI_MAX_REQ_BYTES" ]]; then AI_MAX_REQ_BYTES="$CLI_AI_MAX_REQ_BYTES"; fi
if [[ -n "$CLI_AI_MAX_BODY_BYTES" ]]; then AI_MAX_BODY_BYTES="$CLI_AI_MAX_BODY_BYTES"; fi
if [[ -n "$CLI_AI_IO_TIMEOUT_MS" ]]; then AI_IO_TIMEOUT_MS="$CLI_AI_IO_TIMEOUT_MS"; fi
if [[ -n "$CLI_AI_RATE_LIMIT_RPS" ]]; then AI_RATE_LIMIT_RPS="$CLI_AI_RATE_LIMIT_RPS"; fi
if [[ -n "$CLI_AI_CB_FAIL_THRESHOLD" ]]; then AI_CB_FAIL_THRESHOLD="$CLI_AI_CB_FAIL_THRESHOLD"; fi
if [[ -n "$CLI_AI_CB_COOLDOWN_SEC" ]]; then AI_CB_COOLDOWN_SEC="$CLI_AI_CB_COOLDOWN_SEC"; fi

: "${AI_CORE_DIR:=/var/www/aiir/ai/core}"
: "${AI_RUNTIME_HOST:=127.0.0.1}"
: "${AI_RUNTIME_PORT:=7788}"
: "${AI_DB_EXEC_MODE:=dry-run}"
: "${AI_POLICY_ALLOW_DB_EXEC:=0}"
: "${AI_POLICY_ALLOW_OPS:=}"
: "${AI_WAL_PATH:=/var/www/aiir/ai/state/ai.wal}"
: "${AI_SNAPSHOT_PATH:=/var/www/aiir/ai/state/snapshot.json}"
: "${AI_MAX_REQ_BYTES:=262144}"
: "${AI_MAX_BODY_BYTES:=65536}"
: "${AI_IO_TIMEOUT_MS:=1500}"
: "${AI_RATE_LIMIT_RPS:=60}"
: "${AI_CB_FAIL_THRESHOLD:=20}"
: "${AI_CB_COOLDOWN_SEC:=15}"

export AI_CORE_DIR AI_RUNTIME_HOST AI_RUNTIME_PORT AI_DB_EXEC_MODE
export AI_POLICY_ALLOW_DB_EXEC AI_POLICY_ALLOW_OPS AI_WAL_PATH AI_SNAPSHOT_PATH
export AI_MAX_REQ_BYTES AI_MAX_BODY_BYTES AI_IO_TIMEOUT_MS
export AI_RATE_LIMIT_RPS AI_CB_FAIL_THRESHOLD AI_CB_COOLDOWN_SEC
if [[ ! -x "$RUNTIME_BIN" ]]; then
  /var/www/aiir/server/scripts/build-native-runtime.sh
fi
exec "$RUNTIME_BIN" serve
