#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/var/www/aiir/server/env/ai-runtime.env"
GATEWAY_ENV_FILE="/var/www/aiir/server/env/ai-gateway.env"
TUNING_ENV_FILE="/var/www/aiir/server/env/ai-first-tuning.env"
RUNTIME_BIN="/var/www/aiir/ai/toolchain-native/aiird"

CLI_AI_CORE_DIR="${AI_CORE_DIR-}"
CLI_AI_RUNTIME_HOST="${AI_RUNTIME_HOST-}"
CLI_AI_RUNTIME_PORT="${AI_RUNTIME_PORT-}"
CLI_AI_DB_EXEC_MODE="${AI_DB_EXEC_MODE-}"
CLI_AI_POLICY_ALLOW_DB_EXEC="${AI_POLICY_ALLOW_DB_EXEC-}"
CLI_AI_POLICY_ALLOW_OPS="${AI_POLICY_ALLOW_OPS-}"
CLI_AI_WAL_PATH="${AI_WAL_PATH-}"
CLI_AI_SNAPSHOT_PATH="${AI_SNAPSHOT_PATH-}"
CLI_AI_MAX_REQ_BYTES="${AI_MAX_REQ_BYTES-}"
CLI_AI_MAX_BODY_BYTES="${AI_MAX_BODY_BYTES-}"
CLI_AI_IO_TIMEOUT_MS="${AI_IO_TIMEOUT_MS-}"
CLI_AI_RATE_LIMIT_RPS="${AI_RATE_LIMIT_RPS-}"
CLI_AI_CB_FAIL_THRESHOLD="${AI_CB_FAIL_THRESHOLD-}"
CLI_AI_CB_COOLDOWN_SEC="${AI_CB_COOLDOWN_SEC-}"
CLI_AI_CAP_REQUIRE="${AI_CAP_REQUIRE-}"
CLI_AI_CAP_SECRET="${AI_CAP_SECRET-}"
CLI_AI_CAP_MAX_FUTURE_SEC="${AI_CAP_MAX_FUTURE_SEC-}"
CLI_AI_AUDIT_LOG_PATH="${AI_AUDIT_LOG_PATH-}"
CLI_AI_LOG_REQUESTS="${AI_LOG_REQUESTS-}"
CLI_AIIR_GATEWAY_ENABLE="${AIIR_GATEWAY_ENABLE-}"
CLI_AIIR_PROJECT_AUTOCREATE_DB="${AIIR_PROJECT_AUTOCREATE_DB-}"
CLI_AIIR_HUMAN_DB_MODE="${AIIR_HUMAN_DB_MODE-}"
CLI_AIIR_DB_PROVIDER="${AIIR_DB_PROVIDER-}"
CLI_AIIR_DB_DEFAULT_PROFILE="${AIIR_DB_DEFAULT_PROFILE-}"
CLI_AIIR_DB_REGION="${AIIR_DB_REGION-}"
CLI_AIIR_DB_RETENTION_DAYS="${AIIR_DB_RETENTION_DAYS-}"
CLI_AIIR_DB_REQUIRE_CAPABILITY="${AIIR_DB_REQUIRE_CAPABILITY-}"
CLI_AIIR_DB_AUDIT_ENABLE="${AIIR_DB_AUDIT_ENABLE-}"
CLI_AIIR_DB_ALLOW_DIRECT_CREDENTIALS="${AIIR_DB_ALLOW_DIRECT_CREDENTIALS-}"
CLI_AIIR_PROJECTS_FILE="${AIIR_PROJECTS_FILE-}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
if [[ -f "$GATEWAY_ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$GATEWAY_ENV_FILE"
fi
if [[ -f "$TUNING_ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$TUNING_ENV_FILE"
fi

if [[ -n "$CLI_AI_CORE_DIR" ]]; then AI_CORE_DIR="$CLI_AI_CORE_DIR"; fi
if [[ -n "$CLI_AI_RUNTIME_HOST" ]]; then AI_RUNTIME_HOST="$CLI_AI_RUNTIME_HOST"; fi
if [[ -n "$CLI_AI_RUNTIME_PORT" ]]; then AI_RUNTIME_PORT="$CLI_AI_RUNTIME_PORT"; fi
if [[ -n "$CLI_AI_DB_EXEC_MODE" ]]; then AI_DB_EXEC_MODE="$CLI_AI_DB_EXEC_MODE"; fi
if [[ -n "$CLI_AI_POLICY_ALLOW_DB_EXEC" ]]; then AI_POLICY_ALLOW_DB_EXEC="$CLI_AI_POLICY_ALLOW_DB_EXEC"; fi
if [[ -n "${CLI_AI_POLICY_ALLOW_OPS+x}" ]]; then AI_POLICY_ALLOW_OPS="$CLI_AI_POLICY_ALLOW_OPS"; fi
if [[ -n "$CLI_AI_WAL_PATH" ]]; then AI_WAL_PATH="$CLI_AI_WAL_PATH"; fi
if [[ -n "$CLI_AI_SNAPSHOT_PATH" ]]; then AI_SNAPSHOT_PATH="$CLI_AI_SNAPSHOT_PATH"; fi
if [[ -n "$CLI_AI_MAX_REQ_BYTES" ]]; then AI_MAX_REQ_BYTES="$CLI_AI_MAX_REQ_BYTES"; fi
if [[ -n "$CLI_AI_MAX_BODY_BYTES" ]]; then AI_MAX_BODY_BYTES="$CLI_AI_MAX_BODY_BYTES"; fi
if [[ -n "$CLI_AI_IO_TIMEOUT_MS" ]]; then AI_IO_TIMEOUT_MS="$CLI_AI_IO_TIMEOUT_MS"; fi
if [[ -n "$CLI_AI_RATE_LIMIT_RPS" ]]; then AI_RATE_LIMIT_RPS="$CLI_AI_RATE_LIMIT_RPS"; fi
if [[ -n "$CLI_AI_CB_FAIL_THRESHOLD" ]]; then AI_CB_FAIL_THRESHOLD="$CLI_AI_CB_FAIL_THRESHOLD"; fi
if [[ -n "$CLI_AI_CB_COOLDOWN_SEC" ]]; then AI_CB_COOLDOWN_SEC="$CLI_AI_CB_COOLDOWN_SEC"; fi
if [[ -n "$CLI_AI_CAP_REQUIRE" ]]; then AI_CAP_REQUIRE="$CLI_AI_CAP_REQUIRE"; fi
if [[ -n "$CLI_AI_CAP_SECRET" ]]; then AI_CAP_SECRET="$CLI_AI_CAP_SECRET"; fi
if [[ -n "$CLI_AI_CAP_MAX_FUTURE_SEC" ]]; then AI_CAP_MAX_FUTURE_SEC="$CLI_AI_CAP_MAX_FUTURE_SEC"; fi
if [[ -n "$CLI_AI_AUDIT_LOG_PATH" ]]; then AI_AUDIT_LOG_PATH="$CLI_AI_AUDIT_LOG_PATH"; fi
if [[ -n "$CLI_AI_LOG_REQUESTS" ]]; then AI_LOG_REQUESTS="$CLI_AI_LOG_REQUESTS"; fi
if [[ -n "$CLI_AIIR_GATEWAY_ENABLE" ]]; then AIIR_GATEWAY_ENABLE="$CLI_AIIR_GATEWAY_ENABLE"; fi
if [[ -n "$CLI_AIIR_PROJECT_AUTOCREATE_DB" ]]; then AIIR_PROJECT_AUTOCREATE_DB="$CLI_AIIR_PROJECT_AUTOCREATE_DB"; fi
if [[ -n "$CLI_AIIR_HUMAN_DB_MODE" ]]; then AIIR_HUMAN_DB_MODE="$CLI_AIIR_HUMAN_DB_MODE"; fi
if [[ -n "$CLI_AIIR_DB_PROVIDER" ]]; then AIIR_DB_PROVIDER="$CLI_AIIR_DB_PROVIDER"; fi
if [[ -n "$CLI_AIIR_DB_DEFAULT_PROFILE" ]]; then AIIR_DB_DEFAULT_PROFILE="$CLI_AIIR_DB_DEFAULT_PROFILE"; fi
if [[ -n "$CLI_AIIR_DB_REGION" ]]; then AIIR_DB_REGION="$CLI_AIIR_DB_REGION"; fi
if [[ -n "$CLI_AIIR_DB_RETENTION_DAYS" ]]; then AIIR_DB_RETENTION_DAYS="$CLI_AIIR_DB_RETENTION_DAYS"; fi
if [[ -n "$CLI_AIIR_DB_REQUIRE_CAPABILITY" ]]; then AIIR_DB_REQUIRE_CAPABILITY="$CLI_AIIR_DB_REQUIRE_CAPABILITY"; fi
if [[ -n "$CLI_AIIR_DB_AUDIT_ENABLE" ]]; then AIIR_DB_AUDIT_ENABLE="$CLI_AIIR_DB_AUDIT_ENABLE"; fi
if [[ -n "$CLI_AIIR_DB_ALLOW_DIRECT_CREDENTIALS" ]]; then AIIR_DB_ALLOW_DIRECT_CREDENTIALS="$CLI_AIIR_DB_ALLOW_DIRECT_CREDENTIALS"; fi
if [[ -n "$CLI_AIIR_PROJECTS_FILE" ]]; then AIIR_PROJECTS_FILE="$CLI_AIIR_PROJECTS_FILE"; fi

: "${AI_CORE_DIR:=/var/www/aiir/ai/core}"
: "${AI_RUNTIME_HOST:=127.0.0.1}"
: "${AI_RUNTIME_PORT:=7788}"
: "${AI_DB_EXEC_MODE:=dry-run}"
: "${AI_POLICY_ALLOW_DB_EXEC:=0}"
: "${AI_POLICY_ALLOW_OPS:=}"
: "${AI_WAL_PATH:=/var/www/aiir/ai/state/ai.wal}"
: "${AI_SNAPSHOT_PATH:=/var/www/aiir/ai/state/snapshot.json}"
: "${AI_MAX_REQ_BYTES:=262144}"
: "${AI_MAX_BODY_BYTES:=65536}"
: "${AI_IO_TIMEOUT_MS:=1500}"
: "${AI_RATE_LIMIT_RPS:=60}"
: "${AI_CB_FAIL_THRESHOLD:=20}"
: "${AI_CB_COOLDOWN_SEC:=15}"
: "${AI_CAP_REQUIRE:=0}"
: "${AI_CAP_SECRET:=}"
: "${AI_CAP_MAX_FUTURE_SEC:=120}"
: "${AI_AUDIT_LOG_PATH:=/var/www/aiir/ai/log/runtime_audit.log}"
: "${AI_LOG_REQUESTS:=1}"
: "${AIIR_GATEWAY_ENABLE:=1}"
: "${AIIR_PROJECT_AUTOCREATE_DB:=1}"
: "${AIIR_HUMAN_DB_MODE:=indirect}"
: "${AIIR_DB_PROVIDER:=default}"
: "${AIIR_DB_DEFAULT_PROFILE:=default}"
: "${AIIR_DB_REGION:=local}"
: "${AIIR_DB_RETENTION_DAYS:=30}"
: "${AIIR_DB_REQUIRE_CAPABILITY:=1}"
: "${AIIR_DB_AUDIT_ENABLE:=1}"
: "${AIIR_DB_ALLOW_DIRECT_CREDENTIALS:=0}"
: "${AIIR_PROJECTS_FILE:=/var/www/aiir/ai/state/projects.ndjson}"

export AI_CORE_DIR AI_RUNTIME_HOST AI_RUNTIME_PORT AI_DB_EXEC_MODE
export AI_POLICY_ALLOW_DB_EXEC AI_POLICY_ALLOW_OPS AI_WAL_PATH AI_SNAPSHOT_PATH
export AI_MAX_REQ_BYTES AI_MAX_BODY_BYTES AI_IO_TIMEOUT_MS
export AI_RATE_LIMIT_RPS AI_CB_FAIL_THRESHOLD AI_CB_COOLDOWN_SEC
export AI_CAP_REQUIRE AI_CAP_SECRET AI_CAP_MAX_FUTURE_SEC AI_AUDIT_LOG_PATH
export AI_LOG_REQUESTS
export AIIR_GATEWAY_ENABLE AIIR_PROJECT_AUTOCREATE_DB AIIR_HUMAN_DB_MODE
export AIIR_DB_PROVIDER AIIR_DB_DEFAULT_PROFILE AIIR_DB_REGION AIIR_DB_RETENTION_DAYS
export AIIR_DB_REQUIRE_CAPABILITY AIIR_DB_AUDIT_ENABLE AIIR_DB_ALLOW_DIRECT_CREDENTIALS AIIR_PROJECTS_FILE
if [[ ! -x "$RUNTIME_BIN" ]]; then
  /var/www/aiir/server/scripts/build-native-runtime.sh
fi
exec "$RUNTIME_BIN" serve
